version: '3'
services:
  motorhead:
    build: ./
    ports:
      - '8081:8081'
    environment:
      PORT: 8081
      MOTORHEAD_MAX_WINDOW_SIZE: 25
      MOTORHEAD_LONG_TERM_MEMORY: 'true'
      MOTORHEAD_MODEL: 'gpt-3.5-turbo'
      REDIS_URL: ${REDIS_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY_MOTORHEAD}

